"""Turning the dataset into LaTeX.

The rule the project is built around: no number appears literally in the prose
of the report. Every quantity the text quotes is a macro defined here from
results.json, so a number in a sentence and the same number in a table cannot
disagree, and re-running the sweep updates the prose along with the figures.
tools/check_numbers.py enforces it by refusing to pass if a bare numeral turns
up in a sentence where a macro belongs.

Two things follow from that rule and are worth stating.

A macro whose data is missing must still be defined, or the report will not
compile at all — one absent experiment would take down the whole document. Every
macro therefore has a fallback that renders visibly, as an em dash with a
footnote-ready reason, rather than a zero that reads like a measurement.

Formatting belongs here, not in the text. Cycle counts are integers, per-byte
costs carry three decimals, ratios carry two, and a quantity that was measured
with an interval always prints with it. That way a reader never has to wonder
whether a bare number was rounded in the prose or in the data.
"""
from __future__ import annotations

import math
from typing import Any

from . import model

MISSING = r"\textemdash{}"

# LaTeX control sequences are letters only, so a cipher name cannot be turned
# into a macro name by mechanical transformation: "aes-256-gcm" would give
# \fitAAes256GcmHw, which TeX will not accept. The mapping is therefore
# explicit, with a fallback that spells out any digits in a name added later so
# a new cipher cannot silently produce an uncompilable document.
CIPHER_TAG = {
    "aes-256-gcm":          "AesGcm",
    "chacha20-poly1305":    "ChaPoly",
    "lr-aes-256-gcm":       "LrAesGcm",
    "lr-chacha20-poly1305": "LrChaPoly",
    "null":                 "Null",
}
_DIGIT_WORDS = ["Zero", "One", "Two", "Three", "Four",
                "Five", "Six", "Seven", "Eight", "Nine"]


def cipher_tag(name: str) -> str:
    if name in CIPHER_TAG:
        return CIPHER_TAG[name]
    out = []
    for word in name.replace("-", " ").replace("_", " ").split():
        piece = "".join(_DIGIT_WORDS[int(ch)] if ch.isdigit() else ch
                        for ch in word if ch.isalnum())
        out.append(piece[:1].upper() + piece[1:])
    return "".join(out) or "Unknown"


def _fmt(value: float | None, digits: int = 0, unit: str = "") -> str:
    if value is None or (isinstance(value, float) and not math.isfinite(value)):
        return MISSING
    if digits == 0:
        s = f"{value:,.0f}".replace(",", r"\,")
    else:
        s = f"{value:.{digits}f}"
    return s + (f"\\,{unit}" if unit else "")


def _pct(value: float | None, digits: int = 1) -> str:
    if value is None or not math.isfinite(value):
        return MISSING
    return f"{value * 100:.{digits}f}\\%"


def _tex_escape(s: str) -> str:
    out = []
    for ch in str(s):
        if ch in "#$%&_{}":
            out.append("\\" + ch)
        elif ch == "\\":
            out.append(r"\textbackslash{}")
        elif ch == "~":
            out.append(r"\textasciitilde{}")
        elif ch == "^":
            out.append(r"\textasciicircum{}")
        else:
            out.append(ch)
    return "".join(out)


class Macros:
    """Accumulates \\newcommand definitions and keeps their names unique."""

    def __init__(self) -> None:
        self._defs: dict[str, str] = {}

    def set(self, name: str, value: str) -> None:
        if name in self._defs and self._defs[name] != value:
            raise ValueError(f"macro {name} defined twice with different values")
        self._defs[name] = value

    def num(self, name: str, value: float | None, digits: int = 0, unit: str = "") -> None:
        self.set(name, _fmt(value, digits, unit))

    def pct(self, name: str, value: float | None, digits: int = 1) -> None:
        self.set(name, _pct(value, digits))

    def text(self, name: str, value: Any) -> None:
        self.set(name, _tex_escape(value))

    def render(self) -> str:
        lines = [
            "% Generated by python/lr/report.py from results/results.json.",
            "% Do not edit: every value here is derived from measured data, and",
            "% editing one would put the prose and the tables into disagreement.",
            "",
        ]
        for name in sorted(self._defs):
            lines.append(f"\\newcommand{{\\{name}}}{{{self._defs[name]}}}")
        return "\n".join(lines) + "\n"

    def names(self) -> list[str]:
        return sorted(self._defs)


# ---------------------------------------------------------------------------
# Tables
# ---------------------------------------------------------------------------

def table_cost_model(data: dict) -> str:
    """The fitted cost model, one row per cipher and hardware-crypto level."""
    pts = data.get("e1", {}).get("points", [])
    if not pts:
        return "% e1 unavailable\n"
    rows = []
    for cipher in sorted({p["cipher"] for p in pts}):
        for hw in (True, False):
            if not any(p["cipher"] == cipher and bool(p["hw_crypto"]) == hw for p in pts):
                continue
            f = model.fit_from_points(pts, cipher, hw)
            if not f.ok:
                continue
            rows.append(
                f"{_tex_escape(cipher)} & {'yes' if hw else 'no'} & "
                f"{_fmt(f.a, 0)} & {_fmt(f.b, 3)} & "
                f"{_fmt(f.s_star, 0)} & "
                f"[{_fmt(f.s_star_ci[0], 0)}, {_fmt(f.s_star_ci[1], 0)}] & "
                f"{f.r_squared:.4f} \\\\")
    body = "\n".join(rows) if rows else "\\multicolumn{7}{c}{no stable fits} \\\\"
    return (
        "\\begin{tabular}{llrrrrr}\n\\toprule\n"
        "cipher & hw & $a$ (cyc) & $b$ (cyc/B) & $s^{*}$ (B) & 95\\% CI & $R^2$ \\\\\n"
        "\\midrule\n" + body + "\n\\bottomrule\n\\end{tabular}\n")


def table_iopath(data: dict) -> str:
    pts = [p for p in data.get("e3", {}).get("points", []) if p.get("ok")]
    if not pts:
        return "% e3 unavailable\n"
    payload = max(p["payload_bytes"] for p in pts)
    sel = [p for p in pts if p["payload_bytes"] == payload]
    rows = []
    for backend in sorted({p["backend"] for p in sel}):
        for p in sorted([q for q in sel if q["backend"] == backend],
                        key=lambda q: q["batch"]):
            rows.append(f"{_tex_escape(backend)} & {p['batch']} & "
                        f"{_fmt(p['cycles_median'], 0)} & "
                        f"{p['syscalls_per_packet']:.3f} & "
                        f"{_fmt(p['pps_median'], 0)} \\\\")
    return ("\\begin{tabular}{lrrrr}\n\\toprule\n"
            "backend & $B$ & cycles/pkt & syscalls/pkt & pkt/s \\\\\n\\midrule\n"
            + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")


def table_controls(data: dict) -> str:
    checks = data.get("controls", {}).get("checks", [])
    if not checks:
        return "% controls unavailable\n"
    rows = []
    for c in checks:
        verdict = "pass" if c.get("passed") else ("not run" if not c.get("ran") else "\\textbf{fail}")
        detail = c.get("outcome") or c.get("error") or ""
        rows.append(f"{_tex_escape(c['name'])} & {verdict} & "
                    f"\\footnotesize {_tex_escape(detail)} \\\\")
    return ("\\begin{tabular}{@{}p{0.30\\linewidth}lp{0.52\\linewidth}@{}}\n\\toprule\n"
            "control & verdict & outcome \\\\\n\\midrule\n"
            + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")


def table_environment(data: dict) -> str:
    env = data.get("environment", {})
    if not env:
        return "% environment unavailable\n"
    fields = [
        ("CPU", env.get("cpu_model", "")),
        ("architecture", env.get("arch", "")),
        ("physical cores", env.get("physical_cores", "")),
        ("SMT", "on" if env.get("smt_enabled") else "off"),
        ("kernel", env.get("os", "")),
        ("counter", f"{env.get('clock_source','')} at "
                    f"{env.get('tsc_hz',0)/1e9:.3f} GHz, "
                    f"{'invariant' if env.get('invariant_tsc') else 'not invariant'}"),
        ("governor", env.get("governor", "")),
        ("kernel isolation", ", ".join(
            [k for k, v in (("isolcpus", env.get("isolcpus")),
                            ("nohz\\_full", env.get("nohz_full")),
                            ("rcu\\_nocbs", env.get("rcu_nocbs"))) if v]) or "none"),
        ("interface", f"{env.get('nic_name','')} ({env.get('nic_driver','')})"),
        ("isolation tier", env.get("isolation_tier", "")),
        ("OpenSSL", env.get("openssl_version", "")),
        ("compiler", env.get("compiler", "")),
        ("flags", env.get("cxx_flags", "")),
        ("host class", env.get("host_class", "")),
    ]
    rows = [f"{k} & {_tex_escape(v)} \\\\" for k, v in fields]
    # The value column wraps: several of these are long strings (a CPU model, a
    # compiler flag list) and a fixed-width column would run off the page.
    return ("\\begin{tabular}{@{}lp{0.62\\linewidth}@{}}\n\\toprule\n"
            "property & value \\\\\n\\midrule\n"
            + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")


def table_virtualization(data: dict) -> str:
    tiers = [t for t in data.get("e7", {}).get("tiers", []) if t.get("ok")]
    if not tiers:
        return "% e7 unavailable\n"
    rows = [f"{_tex_escape(t['tier'])} & {_tex_escape(t.get('nic_driver',''))} & "
            f"{_fmt(t['cycles_median'], 0)} & {t.get('relative_to_host', 0):.3f} & "
            f"{t.get('syscalls_per_packet', 0):.3f} \\\\" for t in tiers]
    return ("\\begin{tabular}{llrrr}\n\\toprule\n"
            "tier & driver & cycles/pkt & vs.\\ host & syscalls/pkt \\\\\n\\midrule\n"
            + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")


def table_scaling(data: dict) -> str:
    pts = [p for p in data.get("e2", {}).get("points", []) if p.get("ok")]
    if not pts:
        return "% e2 unavailable\n"
    rows = [f"{p['shards']} & {p['strong_speedup']:.3f} & "
            f"{p['strong_efficiency']:.3f} & {p['weak_efficiency']:.3f} & "
            f"{_fmt(p['cycles_per_packet_strong'], 0)} \\\\"
            for p in sorted(pts, key=lambda q: q["shards"])]
    return ("\\begin{tabular}{rrrrr}\n\\toprule\n"
            "shards & strong speedup & strong eff. & weak eff. & cycles/pkt \\\\\n"
            "\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")


def table_baselines(data: dict) -> str:
    e6 = data.get("e6", {})
    net = data.get("e6_network", {})
    rows = []
    for entry in e6.get("openssl_speed", []):
        if entry.get("ok"):
            rows.append(f"openssl speed, {_tex_escape(entry['cipher'])} & "
                        f"{entry['cycles_per_byte']:.4f} & one & bulk, no framing \\\\")
    for entry in e6.get("linerate", []):
        rows.append(f"linerate, {_tex_escape(entry['cipher'])} & "
                    f"{entry.get('cycles_per_byte_per_pass', 0):.4f} & two & "
                    f"decrypt and re-encrypt \\\\")
    for key, label in (("iperf3_gbps", "iperf3 over UDP, no crypto"),
                       ("wireguard_gbps", "WireGuard tunnel"),
                       ("linerate_gbps", "linerate over the same link")):
        if key in net:
            rows.append(f"{label} & \\multicolumn{{1}}{{c}}{{\\textemdash}} & "
                        f"\\multicolumn{{1}}{{c}}{{\\textemdash}} & "
                        f"{net[key]:.2f}\\,Gb/s on the wire \\\\")
    if not rows:
        return "% e6 unavailable\n"
    return ("\\begin{tabular}{lrll}\n\\toprule\n"
            "reference & cyc/B & passes & note \\\\\n\\midrule\n"
            + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")


TABLES = {
    "cost_model": table_cost_model,
    "iopath": table_iopath,
    "controls": table_controls,
    "environment": table_environment,
    "virtualization": table_virtualization,
    "scaling": table_scaling,
    "baselines": table_baselines,
}


# ---------------------------------------------------------------------------
# Macros
# ---------------------------------------------------------------------------

def build_macros(data: dict, figure_facts: dict) -> Macros:
    m = Macros()
    env = data.get("environment", {})

    # Environment
    m.text("envCPU", env.get("cpu_model", "unknown"))
    m.text("envArch", env.get("arch", "unknown"))
    m.text("envOS", env.get("os", "unknown"))
    m.text("envCompiler", env.get("compiler", "unknown"))
    m.text("envOpenSSL", env.get("openssl_version", "unknown"))
    m.text("envHostClass", env.get("host_class", "unknown"))
    m.text("envIsolationTier", env.get("isolation_tier", "unknown"))
    m.text("envNICDriver", env.get("nic_driver", "unknown"))
    m.text("envGitCommit", env.get("git_commit", "unversioned"))
    m.num("envCores", env.get("physical_cores"))
    m.num("envTSCGHz", (env.get("tsc_hz") or 0) / 1e9, 3)
    m.num("envReplicates", env.get("run", {}).get("replicates"))
    m.pct("envCVThreshold", env.get("run", {}).get("cv_threshold", 0.0), 0)

    # Protocol constants, so the text can never quote a stale header size.
    proto = env.get("protocol", {})
    m.num("protoHeaderBytes", proto.get("header_bytes"))
    m.num("protoTagBytes", proto.get("tag_bytes"))
    m.num("protoMaxPayload", proto.get("max_payload_bytes"))
    m.num("protoMTU", proto.get("mtu_bytes"))
    m.num("protoIPUDPOverhead", proto.get("ip_udp_overhead_bytes"))

    # E1: one set of macros per cipher and hardware level, plus the headline.
    pts = data.get("e1", {}).get("points", [])
    best_hw = None
    for cipher in sorted({p["cipher"] for p in pts}):
        tag = cipher_tag(cipher)
        for hw in (True, False):
            if not any(p["cipher"] == cipher and bool(p["hw_crypto"]) == hw for p in pts):
                continue
            f = model.fit_from_points(pts, cipher, hw)
            suffix = "Hw" if hw else "Masked"
            m.num(f"fitA{tag}{suffix}", f.a if f.ok else None)
            m.num(f"fitB{tag}{suffix}", f.b if f.ok else None, 3)
            m.num(f"fitSStar{tag}{suffix}", f.s_star if f.ok else None)
            m.num(f"fitSStarLo{tag}{suffix}", f.s_star_ci[0] if f.ok else None)
            m.num(f"fitSStarHi{tag}{suffix}", f.s_star_ci[1] if f.ok else None)
            m.num(f"fitRsq{tag}{suffix}", f.r_squared if f.ok else None, 4)
            m.num(f"fitN{tag}{suffix}", f.n if f.ok else None)
            m.text(f"fitCurvature{tag}{suffix}", f.curvature_note or "not evaluated")
            if hw and f.ok and (best_hw is None or f.a < best_hw[1].a):
                best_hw = (cipher, f)

    if best_hw:
        m.text("bestCipher", best_hw[0])
        m.num("bestA", best_hw[1].a)
        m.num("bestB", best_hw[1].b, 3)
        m.num("bestSStar", best_hw[1].s_star)
    else:
        for name in ("bestA", "bestB", "bestSStar"):
            m.set(name, MISSING)
        m.set("bestCipher", MISSING)

    e1 = data.get("e1", {})
    m.pct("anchorDrift", e1.get("anchor_drift"), 2)
    m.text("anchorVerdict", "valid" if e1.get("anchor_ok") else "void")
    m.num("eOneUnits", len(pts))

    # The comparison the report leads on: our implementation against OpenSSL's.
    def _fit(c, hw=True):
        return model.fit_from_points(pts, c, hw) if pts else None
    ours, theirs = _fit("lr-aes-256-gcm"), _fit("aes-256-gcm")
    if ours and theirs and ours.ok and theirs.ok and theirs.b > 0:
        m.num("simdVsOpensslB", ours.b / theirs.b, 2)
        m.num("simdVsOpensslA", ours.a / theirs.a if theirs.a else None, 2)
    else:
        m.set("simdVsOpensslB", MISSING)
        m.set("simdVsOpensslA", MISSING)

    # E2
    e2 = data.get("e2", {})
    sc = figure_facts.get("scaling", {})
    m.num("scaleMaxShards", sc.get("max_shards", e2.get("max_shards")))
    m.num("scaleSerialFraction", sc.get("serial_fraction"), 4)
    m.text("scalePool", e2.get("pool", "unknown"))
    e2m = data.get("e2_mpi", {})
    m.num("mpiRanks", e2m.get("ranks") if e2m.get("available") else None)
    m.num("mpiHosts", e2m.get("distinct_hosts") if e2m.get("available") else None)
    m.num("mpiCoordNs", e2m.get("coordination_ns_per_iteration")
          if e2m.get("available") else None, 0)

    # E3
    e3 = data.get("e3", {})
    m.num("ioPosixCycles", e3.get("posix_b1_cycles"))
    m.num("ioSqpollCycles", e3.get("sqpoll_b1_cycles"))
    m.num("ioBoundaryCycles", e3.get("posix_minus_sqpoll_b1_cycles"))
    m.text("ioSqpollNote", e3.get("sqpoll_interpretation", "not evaluated"))
    m.text("ioBestBatched", e3.get("best_batched_backend", "none"))
    m.num("ioBestBatchedCycles", e3.get("best_batched_cycles"))

    # E4
    e4 = data.get("e4", {})
    m.num("memSustainedGBps", e4.get("stream_bandwidth_gbps"), 1)
    m.num("memRoofGBps", e4.get("roof_payload_gbps"), 2)
    m.num("memPasses", e4.get("payload_passes_total"))

    # E5
    e5 = data.get("e5", {})
    m.num("latCapacityPPS", e5.get("capacity_pps"))
    m.num("latKneePPS", e5.get("knee_pps"))
    m.pct("latKneeFraction", e5.get("knee_fraction"))
    m.text("latTopology", e5.get("topology", "unknown"))
    m.text("latNetem", e5.get("netem_label", "none"))
    m.text("latInterpretation", e5.get("interpretation_note", "not evaluated"))

    # E6
    e6 = data.get("e6", {})
    ossl = next((r for r in e6.get("openssl_speed", []) if r.get("ok")), None)
    m.num("refOpensslCycPerByte", ossl.get("cycles_per_byte") if ossl else None, 4)
    lr0 = next(iter(e6.get("linerate", [])), None)
    m.num("refOursCycPerByte", lr0.get("cycles_per_byte_per_pass") if lr0 else None, 4)
    net = data.get("e6_network", {})
    m.num("refIperfGbps", net.get("iperf3_gbps"), 2)
    m.num("refWireGuardGbps", net.get("wireguard_gbps"), 2)
    m.num("refLinerateGbps", net.get("linerate_gbps"), 2)

    # E7
    e7 = data.get("e7", {})
    m.num("virtTiers", e7.get("tiers_measured"))
    m.num("virtChainPerHop", e7.get("chain_cycles_per_hop"))
    tiers = {t["tier"]: t for t in e7.get("tiers", []) if t.get("ok")}
    for tier in ("host", "netns", "container", "gvisor"):
        t = tiers.get(tier)
        name = tier.capitalize()
        m.num(f"virt{name}Cycles", t.get("cycles_median") if t else None)
        m.num(f"virt{name}Relative", t.get("relative_to_host") if t else None, 3)

    # E8
    e8 = data.get("e8", {})
    if e8.get("available"):
        m.text("gpuDevice", e8.get("device", "unknown"))
        m.num("gpuLaunchNs", e8.get("launch_fixed_ns"), 0)
        m.num("gpuMarginalNs", e8.get("marginal_ns_per_packet"), 3)
        m.num("gpuWorthwhileBatch", e8.get("worthwhile_batch_packets"))
    else:
        m.set("gpuDevice", MISSING)
        for n in ("gpuLaunchNs", "gpuMarginalNs", "gpuWorthwhileBatch"):
            m.set(n, MISSING)

    # E9
    e9 = data.get("e9", {})
    if e9.get("available"):
        m.num("mlSamples", e9.get("n_samples"))
        m.num("mlTestRSquared", e9.get("test_r2"), 3)
        m.num("mlBaselineRSquared", e9.get("baseline_r2"), 3)
        m.pct("mlAdmissionGain", e9.get("admission_gain"))
        m.text("mlBestModel", e9.get("best_model", "unknown"))
    else:
        for n in ("mlSamples", "mlTestRSquared", "mlBaselineRSquared", "mlAdmissionGain"):
            m.set(n, MISSING)
        m.set("mlBestModel", MISSING)

    # Controls
    ctl = data.get("controls", {})
    m.num("ctlRan", ctl.get("ran"))
    m.num("ctlPassed", ctl.get("passed"))
    m.num("ctlNullFixed", ctl.get("null_fixed_cycles"))
    m.num("ctlAEADOnlyFixed", ctl.get("aead_only_fixed_cycles"))
    m.num("ctlAEADFixed", ctl.get("aead_fixed_cycles"))
    m.text("ctlPerByteIdentifiable",
           "yes" if ctl.get("per_byte_identifiable") else "no")
    m.num("ctlAnchorReplicates", data.get("e1", {}).get("anchor_replicates"))

    # Provenance
    prov = data.get("provenance", {})
    m.num("provFragments", len(prov.get("fragments_present", [])))
    m.text("provMissing", ", ".join(prov.get("fragments_missing", [])) or "none")
    return m


def build(data: dict, figure_facts: dict) -> dict[str, str]:
    """Return the generated files, keyed by filename."""
    out = {"macros.tex": build_macros(data, figure_facts).render()}
    for name, fn in TABLES.items():
        try:
            out[f"table_{name}.tex"] = fn(data)
        except Exception as exc:                      # noqa: BLE001
            out[f"table_{name}.tex"] = (
                f"% table '{name}' could not be generated: "
                f"{type(exc).__name__}: {exc}\n"
                "\\emph{This table could not be generated from the dataset.}\n")
    return out
